### ISSUE TITLE
something's not working

### ISSUE THREAD

**Issue by atavreth** [TheFatRabbit/glimmer-and-gloom-very-hard-solver#1]
Hi! Your solver sounds like a really helpful & interesting idea, but I ran into some problems. It's been a long time since I've done anything with python, so I don't really know what went wrong exactly, but here's what happened in the command prompt when I tried to run the program. Do you know what could be the problem?
[gg_solver_problems.txt](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/files/13476186/gg_solver_problems.txt)

**Comment by TheFatRabbit** [comment]
After you took the screenshots of each tile, did you change anything about the game board? For instance, did you scroll up/down the page or change the browser's resolution? It is also possible that the ImageGrab in line 240 did not work. Ensure the board bounds specified in the `config.json` file are correct. If none of this helps, please provide me with the `config.json` file, the tile screenshots (`glimmer.png` and `gloom.png`), and the resolution of your monitor. I have not been able to reproduce the problem on my own machine, but hopefully, with the additional info, I will be able to reproduce it and find a fix. If you made changes to lines 17-20 of `very_hard_solver.py`, please include those lines as well.

**Comment by atavreth** [comment]
I double checked and the coordinates should be correct. I used the physical value that MPos gave me, not scaled or relative. I tried taking different screenshots of the glimmer and gloom tiles as well, but that didn't change anything. The resolution of my monitor is 2560x1440px. I didn't make any changes to lines 17-20. Not sure if it's relevant, but I'm using Windows 10 and a three-monitor-setup. Thank you for taking the time to get this sorted out!
![gloom](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/assets/152188642/73059c19-42b6-44b2-b044-4cfe21987b3a)
![glimmer](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/assets/152188642/159db810-e8d8-42e5-b683-ac07b6d81702)

[config.json](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/files/13478956/config.json)

**Comment by TheFatRabbit** [comment]
Unfortunately, the issue is likely one with the monitor's resolution, as creation and testing was done only on 1920x1080 screens. While the program uses what I assumed to be common proportions across all devices in order to determine the locations of each individual pixel, it is possible that Flight Rising changes the background and/or pixel sizes based on the size of the board. If possible, could you send me a screenshot of your whole board? I should be able to compare it against my own board to determine what changes, if anything, across resolutions. If it is possible for you to set up and run the program on a 1920x1080 monitor, you may be able to work the program there for the time being. I will look into support for more monitors as soon as I can.

**Comment by atavreth** [comment]
Looks like the screen I was using was part of the problem, I tried it on a different monitor with 1920x1080 resolution and it gave me a different shorter error message. Here's the board on my 2560x1440 monitor and the new error message:
![2560x1440_screenshot](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/assets/152188642/29d50afb-9019-4dec-a9fe-6b671fba0d71)
[new error message.txt](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/files/13480112/new.error.message.txt)

**Comment by atavreth** [comment]
Sorry, disregard the new error message, I just typed in a number wrong. I still get the old error message even on the 1920x1080 screen.

**Comment by TheFatRabbit** [comment]
Could you send your new `config.json` and a screenshot of the board?

**Comment by atavreth** [comment]
This is on the 1920x1080 monitor, same error as on the other monitor:

[config.json](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/files/13480357/config.json)
![1920x1080_screenshot](https://github.com/TheFatRabbit/glimmer-and-gloom-very-hard-solver/assets/152188642/d7eee6b4-48af-4427-bfc5-a0518a1150f9)

**Comment by TheFatRabbit** [comment]
Both images you sent lined up perfectly when I overlaid one over the other and resized them while preserving the aspect ratio, so the monitor resolution is _probably_ not the issue. It may have something to do with using multiple monitors. If you are able to test this theory by switching temporarily to a single monitor setup please do, but if this would be tough to do with your PC's setup, I can test it myself as soon as I get a larger chunk of free time to dedicate to the project (possibly tonight EST, but more likely tomorrow or the next day). Sorry about the issues you are having!

**Comment by atavreth** [comment]
I just tried running it on my laptop (1600x900 I think) and it gave me the exact same error message as before... maybe I'm doing something wrong when following the readme? When I first tried it out pip install didn't work, so I installed python again and ticked the "Add Python to PATH" and "Add Python to environment variables" checkboxes, that seemed to fix it. Windows on both my laptop and my PC are set to german, but that has never been a problem before I think. I can't think of anything else that might be relevant at this point :/

**Comment by TheFatRabbit** [comment]
I don't have time tonight, but I'll be able to test whether or not it works
on two monitors tomorrow night. The errors you are getting are unrelated to
the imports, so the program has gotten past that point in its execution.
There is likely an error with my globalization of the math, as all other
programs I have made have been for my computer only. It is also possible
that my proportions are just wrong enough (since I did them manually) so
there's likely a large error that builds up as a user's environment becomes
more different from my own.

**Comment by TheFatRabbit** [comment]
While investigating this issue, I found a few other possible issues and made a few changes. I will be pushing those as soon as I can (specifically one that allows ImageGrab to grab from pixel locations on other monitors, which would have been a problem had the issue you are currently having not turned up). The issue you were having seems to be related to PyAutoGUI throwing an error when it fails to locate a tile, rather than instead returning a None value which the if statement interprets as the tile not being of that color (see lines 247-253 if you are interested). The return of a None value occurred on both my laptop and PC, and I have not heard of anyone else having a similar issue. This may be related to the version of Pillow or PyAutoGUI you have installed. In the command prompt, run `pip list --outdated` and update either one should they be out of date (`pip install <Pillow/PyAutoGUI> --upgrade`). Let me know if this works. If not, you should be able to replace:
Line 248 with
```if find_image_without_error(os.path.join(dirname, "glimmer.png"), image, confidence=config["confidence"]):```
Line 250 with
```elif find_image_without_error(os.path.join(dirname, "gloom.png"), image, confidence=config["confidence"]):```
and add the following function (I put it right above solve_board around line 211):
```
def find_image_without_error(image_location, image, confidence):
    try:
        found_image = pyautogui.locate(image_location, image, confidence=confidence)
        return found_image
    except pyautogui.ImageNotFoundException:
        return None
```

**Comment by atavreth** [comment]
It's working perfectly now! Thank you so much!

Pillow and PyAutoGUI were up to date, but I added your code (I'm pretty sure the if and elif statements are supposed to replace line 241 and 243 before adding the function to line 211, I think they're on lines 248 and 250 after adding the function), set the confidence to 0.5 and it worked!

**Comment by TheFatRabbit** [comment]
Ah yeah sorry about the line numbers, I forgot to factor in the addition of the function when sending the line numbers. Glad you got it working! I'll continue looking for a fix, as now that I know the problem I should be able to push a solution that works both ways (or figure out why PyAutoGUI is only returning an error some of the time). I'll keep this issue open until I find a permanent solution.
